src/atom_free.cpp: fix ambiguous call
Fix the following build failure raised since
https://github.com/enzo1982/mp4v2/commit/ec9273405e40c5dc3d33e2b45db5ee9ae89174a3:

src/atom_free.cpp: In member function 'virtual void mp4v2::impl::MP4FreeAtom::Write()':
src/atom_free.cpp:46:71: error: call of overloaded 'min(uint64_t, unsigned int)' is ambiguous
         m_File.WriteBytes(freebuf, min(GetSize() - ix, sizeof(freebuf)));
                                                                       ^

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>